platform:
  - Win32
  - Win64

environment:
  home: C:\projects
  matrix:
  - generator : Visual Studio 14
  - generator : Visual Studio 14 Win64

os: Visual Studio 2015

branches:
  only:
    - build_MSVC_14

configuration: Release

before_build:
  - cmd: cmake --version
  - cmd: mkdir build
  - cmd: cd build
  - if %platform%==Win32 set generator=Visual Studio 14
  - if %platform%==Win64 set generator=Visual Studio 14 Win64
  - if %platform%==Win32 set vcplatform=Win32
  - if %platform%==Win64 set vcplatform=x64
  - cmd: echo %platform%
  - cmd: echo %generator%
  - cmd: cmake -G "%generator%" -DCMAKE_INSTALL_PREFIX=..\install ..
  - cmd: dir

build_script:
  - msbuild C:\projects\apriltag\build\AprilTag-crossplatform.sln /p:Platform=%vcplatform%